spring.application.name=crud-basico-java
spring.datasource.url=jdbc:mysql://localhost:3306/crud_java_db?useSSL=false&serverTimzeone=UTC
spring.datasource.username=root
spring.datasource.password=FClBrIAt7